### PR TITLE
12 fetching data twice

### PR DESCRIPTION
**Pull request by jaapterwoerds**
I changed the way retries work by using urllib3 Retry mechanism which has as as a sideeffect the looping is not necessary anymore and data will be fetched only once if there are no errrors

### CODE REVIEW

**Comment by jaapterwoerds** [comment]
Probably also explains why I couldn't get any data in, maybe a form of rate limiting if your hitting the API twice consequently with the same parameters

**Comment by jrdi** [comment]
Thank you for this PR @jaapterwoerds! The change makes completely sense and it's true we are calling twice the API for every single ticker. What a mistake!

Despite that I'm not fully convinced by the retry refactor, especially because sometimes the Yahoo API is responding with 200 on some errors 🤷‍♂️ and the parser failing is triggering the retry itself. 

Can you just submit the changes removing the fetching twice in this PR? You can open another one refactoring the retry if you like.

**Comment by jaapterwoerds** [comment]
Hi @jrdi, no problem I'll do that

**Comment by jaapterwoerds** [comment]
@jrdi  see this one https://github.com/councilofelders/opensignals/pull/14. I'll close this one for now, I'll see if it's possible use the retry mechanism and ensure JSON parsing is only done once. If that's possible I''l reopen this PR

**Pull request closed without merging**
